[variables]
main_domain  = "${domain}"
secret_key   = "${password:50}"
live_secret  = "${password:32}"
postgres_pwd = "${password:32}"
rabbitmq_pwd = "${password:32}"
minio_user   = "${password:20}"
minio_pwd    = "${password:40}"

[[config.domains]]
serviceName = "proxy"
port        = 80
host        = "${main_domain}"

[config.env]
APP_RELEASE          = "v1.3.1"
APP_DOMAIN           = "${main_domain}"
WEB_URL              = "http://${main_domain}"
CORS_ALLOWED_ORIGINS = "http://${main_domain},https://${main_domain}"
SITE_ADDRESS         = ":80"

SECRET_KEY             = "${secret_key}"
LIVE_SERVER_SECRET_KEY = "${live_secret}"

POSTGRES_USER     = "plane"
POSTGRES_PASSWORD = "${postgres_pwd}"
POSTGRES_DB       = "plane"

RABBITMQ_USER     = "plane"
RABBITMQ_PASSWORD = "${rabbitmq_pwd}"
RABBITMQ_VHOST    = "plane"

USE_MINIO             = "1"
AWS_ACCESS_KEY_ID     = "${minio_user}"
AWS_SECRET_ACCESS_KEY = "${minio_pwd}"
AWS_S3_BUCKET_NAME    = "uploads"
AWS_S3_ENDPOINT_URL   = "http://plane-minio:9000"
FILE_SIZE_LIMIT       = "5242880"

DEBUG              = "0"
API_KEY_RATE_LIMIT = "60/minute"
MINIO_ENDPOINT_SSL = "0"
